package com.github.giwiro.database.dao

import java.sql.Connection

import com.github.giwiro.model.Product
import com.github.giwiro.utils.DateUtil

class ProductDAO(conn: Connection) {
  def insert(product: Product): Product = {
    val q =
      """|INSERT INTO product (status, courier, name, url, quantity, with_box, delivery_date, detail, image)
         |VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
         |""".stripMargin
    val stmt = conn.prepareStatement(q)
    stmt.setInt(1, product.statusId)
    stmt.setInt(2, product.courierId)
    stmt.setString(3, product.name)
    stmt.setString(4, product.url)
    stmt.setInt(5, product.quantity)
    stmt.setInt(6, product.withBox)
    stmt.setDate(7, DateUtil.parseDate(product.deliveryDate))
    stmt.setString(8, product.detail.getOrElse(""))
    stmt.setString(9, product.image)

    println("SQL: " + q.toString)

    val rows: Int = stmt.executeUpdate()
    val generatedKeys = stmt.getGeneratedKeys()
    generatedKeys.next();
    val autoGeneratedID = generatedKeys.getInt(1)
    new Product(
      id = Some(autoGeneratedID),
      statusId = product.statusId,
      status = None,
      courierId = product.courierId,
      name = product.name,
      url = product.url,
      quantity = product.quantity,
      withBox = product.withBox,
      deliveryDate = product.deliveryDate,
      detail = product.detail,
      image = product.image)
  }
}
